# electron_xss
# Author : Imagemlt
version: "3"
services:

  server:
    image: suctf_electron_server
    build: ./server
    ports:
      - "5000:80"
    volumes:
      - ./logs:/var/log/nginx
    networks:
      suctf_electron:
        ipv4_address: 172.16.233.111
    restart: always

  bot:
    image: suctf_electron_bot
    build: ./bot
    volumes:
      - ./logs:/var/log/nginx
    networks:
      suctf_electron:
        ipv4_address: 172.16.233.222
    restart: always

networks:
  suctf_electron:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.233.0/24
